name: Yaml Lint

on:
  - workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Get changed files
        id: get_file_changes
        uses: tj-actions/changed-files@v37
        with:
          separator: ' '

      - name: Get new and changed .yaml files in main directory to lint
        id: get_files_to_lint
        shell: bash -l {0}
        run: |
          # Set the command in the $() brackets as an output to use in later steps
          echo "lintees=$(
          # Issue where grep regular expressions don't work as expected on the
          # Github Actions shell, check dbt/models/ folder
          echo \
          $(echo ${{ steps.get_file_changes.outputs.modified_files }} |
          tr -s ' ' '\n' |
          grep -E "\.ya?ml$" |
          tr -s '\n' ' ') \
          $(echo ${{ steps.get_file_changes.outputs.added_files }} |
          tr -s ' ' '\n' |
          grep -E "\.ya?ml$" |
          tr -s '\n' ' ')
          )" >> $GITHUB_OUTPUT

      - name: Lint YAML files
        if: steps.get_files_to_lint.outputs.lintees != ''
        id: lint
        run: |
          yamllint -c .github/workflows/.yamllint.yml ${{ steps.get_files_to_lint.outputs.lintees }}
