name: Looker Data Diff

on:
  - workflow_call

jobs:
  data_diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x' # Replace with your desired Python version

    - name: Install dbtc
      run: |
        apt-get update
        apt-get install -y python3-pip
        python -m pip install -r .github/workflows/requirements.txt

    - name: Install dbt packages
      run: dbt deps

    - name: Test database connection
      run: dbt debug
    
    - name: Get changed files
      id: get_file_changes
      uses: tj-actions/changed-files@v37
      with:
        separator: ' '
    
    - name: Get new and changed .sql files in /models to lint
      id: get_files_to_lint
      shell: bash -l {0}
      run: |
        # Set the command in the $() brackets as an output to use in later steps
        echo "lintees=$(
        # Issue where grep regular expressions don't work as expected on the
        # Github Actions shell, check dbt/models/ folder
        echo \
        $(echo ${{ steps.get_file_changes.outputs.files_modified }} |
        tr -s ' ' '\n' |
        grep -E '^models.*[.]sql$' |
        tr -s '\n' ' ') \
        $(echo ${{ steps.get_file_changes.outputs.files_added }} |
        tr -s ' ' '\n' |
        grep -E '^models.*[.]sql$' |
        tr -s '\n' ' ')
        )" >> $GITHUB_OUTPUT

    # - name: Run Looker Tile Queries Check
    #   run: python get_looker_tile_queries.py