name: Looker Data Diff

on:
  - workflow_call

jobs:
  data_diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x' # Replace with your desired Python version

    - name: Install dbtc
      run: |
        apt-get update
        apt-get install -y python3-pip
        python -m pip install -r .github/workflows/requirements.txt

    - name: Install dbt packages
      run: dbt deps

    - name: Test database connection
      run: dbt debug
    
    - name: Get changed files
      id: get_file_changes
      uses: tj-actions/changed-files@v37
      with:
        separator: ' '
    # - name: Run Looker Tile Queries Check
    #   run: python get_looker_tile_queries.py